services:
  backend:

    build: .
    container_name: tradelens-backend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    container_name: tradelens-db
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/config/db/sql:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    container_name: tradelens-adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  pgdata:
